#!/usr/bin/perl

=head1 NAME

test-daily-process-tarball - process tar ball fro Test::Daily

=head1 SYNOPSIS

=head1 DESCRIPTION

=cut


use strict;
use warnings;

use Getopt::Long;
use Pod::Usage;
use Test::Daily;

exit main();

sub main {
	my $help;
	GetOptions(
		'help|h' => \$help,
	) or pod2usage;
	pod2usage if $help;
	
	my $tarball = shift @ARGV;
	pod2usage if not $tarball;
	
	my $td = Test::Daily->new();
	#$td->extract_tarball($tarball);
	$td->update_site_makefile;
	
	return 0;
}
